//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDetail
    {
        public string ID_Detail { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string ID_Folder { get; set; }
    
        public virtual Folder Folder { get; set; }
    }
}
