//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Folders = new HashSet<Folder>();
        }
        public User(string detail, bool status, string macAddress)
        {
            this.ID_User = macAddress;
            this.Detail = detail;
            this.Status = status;
            this.MacAddress = macAddress;
        }
        public string ID_User { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MacAddress { get; set; }
    
        public virtual ICollection<Folder> Folders { get; set; }
    }
}
