//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Folders = new HashSet<Folder>();
        }
    
        public string ID_User { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> Status { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<Folder> Folders { get; set; }
    }
}
